import turtle
turtle.hideturtle()
turtle.setup(1040, 860)
turtle.speed(1)
turtle.forward(30)
turtle.penup()
turtle.forward(30)
turtle.speed(2)
turtle.pendown()
turtle.forward(30)
turtle.penup()
turtle.speed(3)
turtle.forward(30)
turtle.pendown()
turtle.setheading(90)
turtle.heading()
turtle.speed(4)
turtle.forward(100)
turtle.setheading(180)
turtle.heading()
turtle.speed(5)
turtle.forward(90)
turtle.setheading(270)
turtle.speed(6)
turtle.forward(100)
turtle.bgcolor('red')
turtle.speed(7)
turtle.forward(100)
turtle.circle(80)
turtle.bgcolor('yellow')
turtle.speed(8)
turtle.forward(160)
turtle.dot()
turtle.bgcolor('blue')
turtle.left(120)
turtle.pensize(12)
turtle.forward(40)
turtle.fillcolor('green')
turtle.circle(100)
turtle.left(90)
turtle.speed(9)
turtle.forward(120)
turtle.pencolor('red')
turtle.speed(10)
turtle.circle(100)
#turtle.reset()
turtle.write('Hello')





